#pragma once

#define PANLE_WIDTH 30
#define PANLE_HEIGHT 20

#define DIRECTION_UP 0
#define DIRECTION_LEFT 1
#define DIRECTION_RIGHT 2
#define DIRECTION_DOWN 3

#define BLOCK_WALL 0
#define BLOCK_SNAKE_BODY 1
#define BLOCK_SNAKE_HEAD 2
#define BLOCK_FOOD 3
#define BLOCK_VOID 4
